name: goreleaser

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: Hello
        run: echo "Hello World"
      - if: startsWith(github.ref, 'refs/tags/a/v')
        shell: bash
        run: echo "flags=-f ./a/.goreleaser.yaml" >> $GITHUB_ENV
      - if: startsWith(github.ref, 'refs/tags/b/v')
        shell: bash
        run: echo "flags=-f ./b/.goreleaser.yaml" >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean ${{ env.flags }}

        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
